name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: [bug]
assignees:
  - anton-yurchenko
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - "1.0.0"
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command
      placeholder: "example: version-bump major"
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Content of `.bump` configuration file
      render: toml
    validations:
      required: false
  - type: textarea
    id: log
    attributes:
      label: Execution Log
      render: shell
    validations:
      required: true
  - type: textarea
    id: tags
    attributes:
      label: Git Tags
      description: Output of `git tag` command
      render: shell
    validations:
      required: false
  - type: textarea
    id: sourcecode
    attributes:
      label: Source Code Sample
      placeholder: Provide a relevant parts of the source code and filenames which were suppose to be updated
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
