name: Feature Request
description: Suggest an enhancement to help us improve
title: "[Feature]: "
labels: [feature]
assignees:
  - anton-yurchenko
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      render: markdown
      description: |
        Links? References? Anything that will give us more context.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
